FROM ubuntu:14.04
LABEL maintainer="Millennium Softwares (https://github.com/Millennium-Softwares/)"

ENV VERTICA_VERSION 9.2.0

# Install dev tools
RUN apt-get update -y \
&&  apt-get upgrade -y \
&&  apt-get install -y openssh-server \
                       openssh-client \
                       mcelog \
                       gdb \
                       sysstat \
                       dialog \
                       curl \
&&  apt-get clean

# Set UTF-8 Locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Create Vertica user and set default shell to bash, as required by Vertica
RUN groupadd -r verticadba \
&&  useradd -r -m -g verticadba dbadmin \
&&  chsh -s /bin/bash dbadmin \
&&  chsh -s /bin/bash root \
&&  rm /bin/sh \
&&  ln -s /bin/bash /bin/sh

ENV SHELL "/bin/bash"

# Copy Vertica deb installers
RUN mkdir /srv/setup
COPY software/vertica-console_9.2.0-0_amd64.deb /srv/setup

RUN echo "kernel/mm/transparent_hugepage/enabled = never" >> /etc/sysfs.conf

RUN dpkg -i /srv/setup/vertica-console_9.2.0-0_amd64.deb

RUN rm /srv/setup/vertica-console_9.2.0-0_amd64.deb
RUN rm -R /srv/setup

COPY bootstrap-mc.sh /etc

EXPOSE 5450

RUN ["chmod", "+x", "/etc/bootstrap-mc.sh"]
ENTRYPOINT ["/etc/bootstrap-mc.sh"]
